### ISSUE TITLE
[Question]: What is the difference between this repo and maticjs?

### ISSUE THREAD

**Issue by godeamon** [0xPolygonHermez/zkevm-commonjs#126]
### Version

all

### Description

What is the difference between this repo and maticjs? 
If I want to use js sdk to implement zkevm's token bridge, which library should I use? Because I saw that CliamAsset needs to build proof, do I have to use bridge service or just js sdk?

**Comment by krlosMata** [comment]
Hi !!
This repo, `zkevm-commonjs` contains several utilities for `polygon-zkevm`.
The aim of the repository is to provide basic reference implementation for other production ready repositories, like `maticjs`
In order to use bridge-service the best option is to use the bridge-service and get the proofs from there.

This repository is used in:
- [zkevm-contracts](https://github.com/0xPolygonHermez/zkevm-contracts)
- [zkevm-testvectors](https://github.com/0xPolygonHermez/zkevm-testvectors)
- [zkevm-proverjs](https://github.com/0xPolygonHermez/zkevm-proverjs)
- [zkevm-rom](https://github.com/0xPolygonHermez/zkevm-rom)

**Comment by godeamon** [comment]
Thank you very much, got it!
